### ISSUE TITLE
Sensor submodule

### ISSUE THREAD

**Issue by onyxbits** [naman14/S-Tools#3]
Hi,
it was brought to my attention that you included code from my app "Sensor Readout" (https://github.com/onyxbits/sensorreadout/) in your app without naming me as the author. While it is ok to use my code, using it without giving credit is not (see §4.c of the apache license).

Please restore the copyright information in the com.naman12.stools.sensors package.

**Comment by naman14** [comment]
Hello,
I am sorry for not giving proper credit to you for your effort.I have restored copyright information to the sensor package.
